name: "Release"

on:
  release:
    types: [published, edited]

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: "actions/checkout@v3.5.3"

      - name: Set the version number
        shell: bash
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/wake_spca/manifest.json"

      - name: Archive the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/wake_spca"
          zip wake_spca.zip -r ./

      - name: Upload the archive to the release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/wake_spca/wake_spca.zip
